### ISSUE TITLE
Commands via Webhooks

### ISSUE THREAD

**Issue by raspopov** [PhunStyle/FurBot#14]
Hi! Is it possible to enable bot reaction on commands sent by (specified) webhook also? Seems currently it ignored all commands of other bots. Thank you!

**Comment by PhunStyle** [comment]
Hey there. The official bot doesn't reply to commands from other bots because it can cause cases where it's extremely easy to abuse and overload the bot. If you want to take the (unsupported) plunge and host the bot yourself, you need to remove this line from the code:

https://github.com/PhunStyle/FurBot/blob/master/src/discord.js#L96

Again, i'm not planning to support everyone's bot installs. The set-up guide for the bot, however, is pretty similar to https://github.com/Gravebot/Gravebot/ so feel free to apply the same tutorial to FurBot. 

Lastly, if you don't want to self-host then i'm gonna have to disappoint you; i'm not planning on making FurBot able to react to other bots due to the potential abuse it can cause.
