### ISSUE TITLE
Users can ban themselves

### ISSUE THREAD

**Issue by PhunStyle** [PhunStyle/FurBot#26]
When using f.ban on yourself (if you're a moderator/have the ban users permission) the bot will ban you (removing all your posts in the process).

To avoid accidental bans, mods should not be able to ban themselves. (Ideally mods shouldn't be able to ban other mods).

**Comment by Gideon-Foxo** [comment]
From looking at the code for the ban, softban, and kick commands it would seem that no role hierarchy check at all whatsoever. This is a pretty big vulnerability because as long as a user has ban members perm they can use the bot to ban anyone in the server that the bot is able to ban. This is very much an issue if a server has the bots role at the top of the role hierarchy. You should most likely either 1) Disable the commands until this is fixed or 2) add a role hierarchy check. This would fix the issue of users being able to ban themselves.

**Comment by PhunStyle** [comment]
Ive not worked on discord bot code in a while but thanks for the reply, you're quite right on this. I'm not entirely sure how to check for role hierarchy right now but i think i'd be able to figure it out. 

What you're saying is that if a user is trying to ban a user with a role that is higher on the hierarchy list than theirs it should not have the ban go through? This is easy to do comparing one role with another but users can have several different roles assigned so i'd have to compare each one? I'm already getting confused talking about this.

**Comment by Gideon-Foxo** [comment]
> What you're saying is that if a user is trying to ban a user with a role that is higher on the hierarchy list than theirs it should not have the ban go through?
Correct. Else you could ban everyone but the server owner and yourself. In d.js there is a object for the highest role that a user has https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager?scrollTo=highest. So in otherwords, just find the highest role that a user has then compare it to the other user and if they are same or higher then throw error "you can not do that because they have a role on the same level or higher above you". Hope this helps

**Comment by PhunStyle** [comment]
Thanks again, i will eventually be migrating the bot over to djs but for now it's using an increasingly more outdated library called discordie which i don't think is being maintained anymore. In an update soon i will be disabling the ban command for the time being because of the potential abuse involved.

**Comment by Gideon-Foxo** [comment]
I thought you where maintaining a fork of your own? The lib has not been updated in a few years. Also, you may want to work on moving it to D.js asap! I am really sure discordie will break with the intents which is October 6th iirc
