### ISSUE TITLE
F.shoot is not cute enough and should be made into F.pew

### ISSUE THREAD

**Issue by lockness-Ko** [PhunStyle/FurBot#51]
F.shoot is a very angery term and should be replaced with F.pew

My friends said for me to do this coz they don't have GitHub accounts

**Comment by PhunStyle** [comment]
Thanks for your suggestion and how nice of you to do this for your friends!

Our server is always open as well to submit suggestions and bugs, the invite link can be found when you use the `info` command. Alternatively, you can use the `feedback` command if you don't want to join the server. But GitHub is fine too! The perk of doing this in our server is that the rest of the community can discuss the suggestion as well, so that when something does change, at least the community voted on it.

**Comment by lockness-Ko** [comment]
Thanks for that!
I'll join ur server now!
