### ISSUE TITLE
Building/Self-Hosting documentation is missing

### ISSUE THREAD

**Issue by maxhoesel** [PhunStyle/FurBot#60]
I am currently in the process of setting up my own instance of FurBot for my private servers, however I have run into several issues during the installation. From what I can tell, there is no documentation for installing your own instance of the bot at all, which makes setting up a private instance much harder. 

To clarify, I'm not asking for step-by-step instructions for different operating systems/distributions, but something like a simple dependency list would be very helpful. I'm currently running into all sorts of build errors when trying to install the bot myself with npm 6.13 and newer - having an official dependency list would be very helpful indeed. 

In particular, I would like to see:
- A list of required software (nodejs, redis(?)) with a minimum version number specified
- Maybe a note about the environment that the official bot runs on (Distro, versions, etc...)
- Any other notes that are relevant to self-hosting the bot

Having some documentation about the bots runtime environment would be very helpful for anyone trying to replicate it. Thank you for your consideration :)

**Comment by PhunStyle** [comment]
The reasoning for this is because the bot already runs on a fairly old environment and the base code I used has been discontinued by the original creators, furthermore the API library that's used is also not being maintained anymore.

I never really intended for privatized furbot instances either. Though feel free to hit me up on discord, we can have a chat!
