### ISSUE TITLE
Error: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by VaelophisNyx** [PhunStyle/FurBot#7]
searching `f.e9 wolf stocking female male couple` 
returns the error in the title; exclusively.

**Comment by squashytaur** [comment]
@GalacticRuler, I think this error is being caused because there are no results available for the thing you are searching for (SEE SCREENSHOT BELOW)
![image](https://user-images.githubusercontent.com/28528875/31306344-f7e5908a-ab45-11e7-8283-46c515860106.png)
Try broadening your search or instead use `f.e6` to see if that brings up anything.

**Comment by PhunStyle** [comment]
Hey there, i've committed e972273ce0b0889a077eeb22348efd8c9101b8e7 which should fix this issue. Sadly this means e9 searches are now limited to one tag less.
